### ISSUE TITLE
Will you explain structure?

### ISSUE THREAD

**Issue by at3** [codestation/mhtools#5]
data_install.txt 
Will you explain structure?

**Comment by codestation** [comment]
Let me explain with a example:

0017,0011,00204000

In here the 0017 indicates the binary file that you obtain when the data.bin is unpacked. 
The 0011 indicates the number ending in the data install files.
The 00204000 is the offset where the 0017.bin file is located in the data install number XXXXXXXXXX0011.

If your translated file doesn't exists in the installation data then you use NONE for the 2nd field and FFFFFFFF as the file offset. The plugin will recognize this pattern and skip the file redirection for that chunk of the data install.

My implementation of the data install override isn't perfect since sometimes i made a mistake and the game disables the data install. I still don't have idea about what event triggers it D:

**Comment by at3** [comment]
0017 offsets become 0001D2A000 in DATA.BIN.
What kind of offset is 00204000?
Is it an offset in the ISO?
What should I do to examine it if so?

**Comment by codestation** [comment]
No, the offset used in the data_install.txt is the offset inside one of the various files in the data install folder. For example, try to look the first 16 or 32 bytes of the original and encrypted 0017.bin in the data install files. You will find a match in the XXXXX0011 file at the 0x00204000 offset. You can check the files by hand or code yourself a little script that does the job.

**Comment by at3** [comment]
Splendid.
Thank you, codestation.

**Comment by at3** [comment]
3993,0033,00165800
3994,0033,0017A00
3995,0033,0026200
3996,0033,002F200

Is this right?

**Comment by codestation** [comment]
Looks correct to me (i don't have my psp at hand so i cannot make a data install and check it myself).
